document.addEventListener('DOMContentLoaded', () => {
  const messages = [
    "You are the reason for my smile every day.",
    "I'm here for you, whenever you need.",
    "You light up my life in a unique way.",
    "No matter what happens, I will always be by your side.",
    "Your affection is my refuge.",
    "Together, we can face any challenge",
    "Your love makes me feel complete.",
    "Believe in yourself because I believe in you.",
    "Every moment with you is precious to me.",
    "Your happiness is my priority.",
    "You are the most important person in my life.",
    "Nothing can separate us when we're together.",
    "Being by your side is my favorite place to be.",
    "You are my peace amidst the chaos.",
    "I fell so happy to have you in my life.",
    "Your love is the best gift I could ever receive.",
    "I will always be here to support you, no matter what.",
    "You are the reason I wake up smiling.",
    "Your presence makes everything seem better.",
    "I'm grateful for every moment we share together.",
    "With you, everything is easier.",
    "Your voice is the melody I love to hear.",
    "Your hug is my safe place.",
    "Your happiness is my mission.",
    "you are the best part of my day.",
    "Believe in us because I do.",
    "Every day with you is a new adventure.",
    "I will always be here to listen to you.",
    "You deserve all the happiness in the world.",
    "I'm so grateful to have you in my life.",
    "Wit you, I feel like I can conquer anything.",
    "You are my source of strength and inspiration.",
    "No matter where we arem we are always together.",
    "Your smile lights up my day.",
    "Being with you is the best place to be.",
    "You are the reason I believe in miracles.",
    "Together, we are unstoppable.",
    "I love you more than words can express.",
    "Your affection makes my heart beat fastes.",
    "No matter what happens, I will always be by your side.",
    "You are my refuge and my strength.",
    "Life is better with you in it.",
    "You are my daily joy.",
    "Every moment with you is a gift.",
    "I will always be here to support you in everything.",
    "Your love gives me the courage to face anything.",
    "You are the reason I wake up happy everyday.",
    "I love you just the way you are, perfectly imperfect.",
    "Your smile is the light that guides my way.",
    "You are the best part of my day, every day.",
    "Together, we can face anything.",
    "Your love is the best figt I've ever received.",
    "I'm so happy we found each other.",
    "You are my strength when I need it most.",
    "I will always be here to protect and support you.",
    "You are the reason I believe in love.",
    "Every day with you is a blessing.",
    "Your presence makes the world a better place.",
    "I feel complete with you by my side.",
    "With you, life is more colorful and joyful.",
    "You are the person I always wanted by my side.",
    "I'm here to support you, no matter what happens.",
    "You are the light that brightnes my days.",
    "I will always be by your side, no matter what.",
    "Your affection is the most precious thing to me.",
    "I love you more each day.",
    "You are my home, wherever we are.",
    "Being with you makes my heart happy.",
    "With you, I feel complete.",
    "You are my dream come true.",
    "I am grateful for every moment we spend together.",
    "Your presence is a daily gift in my life.",
    "You are the reason I wake up with a smile on my face.",
    "I will always be here to listen and support you.",
    "You are the best gift life has given me.",
    "With you, every day is a new chance for happiness.",
    "Your love is the light that guides my path.",
    "I love you more than words can express.",
    "Being with you is a dream come true.",
    "You are the best part of my life.",
    "I will always be here to hug you when you need it.",
    "Your smile is my source of joy.",
    "Together, we are stronger than any challenge.",
    "You are the reason I believe in miracles.",
    "I'm so happy we found each other.",
    "Your love makes me feel special and loved.",
    "With you, life is full of possibilities.",
    "You are the most important person in my life.",
    "I love you from the bottom of my heart.",
    "Being with you is the best place in the world.",
    "You are my daily inspiration and motivation.",
    "Your love is the reason I am happy.",
    "I will always be here to support and protect you.",
    "Your presence is the most precious thing to me.",
    "With you, I feel at home.",
    "You are my reason for living and loving.",
    "Every moment with you is a gift.",
    "I love you more than I can express in words.",
    "Being with you is the best gift I've ever received.",
    "You are my reason to smile every day.",
    "I will always be by your side, no matter what.",
    "Your affection and love are all I need.",
    "With you, I feel like I can achieve anything.",
    "You are the person I want to spend the rest of my life with.",
    "Your happiness is my happiness.",
    "I love you more than words can say.",
    "Being with you makes my heart beat faster.",
    "You are my reason for happiness.",
    "I will always be here to support and love you.",
    "You are my source of joy and peace.",
    "Every moment with you is special and unforgettable.",
    "Your love is the light that guides my path.",
    "Being with you is the best place in the world.",
    "You are my reason for waking up with a smile.",
    "I love you more each day.",
    "I will always be here to listen and support you.",
    "Your affection is the best gift I've ever received.",
    "With you, life is full of joy and happiness.",
    "You are the most important person to me.",
    "I'm grateful for every moment we spend together.",
    "Your presence makes my world more beautiful.",
    "Being with you is a dream come true.",
    "I love you from the bottom of my heart.",
    "With you, each day is a new adventure.",
    "You are my source of strength and inspiration.",
    "I will always be here to protect and support you.",
    "Your love is the reason I am happy.",
    "Being by your side is the greatest joy of my life.",
    "You are my reason for smiling every day.",
    "I love you more than words can express.",
    "Your presence is the most precious thing to me.",
    "With you, I feel like I can conquer anything.",
    "You are the person I want to spend my life with.",
    "Being with you makes my heart beat faster.",
    "Your affection is the best gift I've ever received.",
    "I will always be by your side, no matter what.",
    "You are the reason I believe in miracles.",
    "I love you more each day.",
    "Being with you is the greatest joy of my life.",
    "Your happiness is my priority.",
    "With you, everything is easier and more fun.",
    "You are the best part of my day.",
    "I will always be here to support and love you.",
    "Your smile is the light that guides my path.",
    "Being with you is the best place in the world.",
    "You are my source of joy and happiness.",
    "I love you more than I can express in words.",
    "I will always be by your side, no matter what.",
    "Your affection is the most precious thing to me.",
    "With you, I feel like I can achieve anything.",
    "You are the reason I wake up happy every day.",
    "Being with you is a dream come true.",
    "I love you from the bottom of my heart.",
    "Your presence is a daily gift in my life.",
    "With you, every day is a new chance for happiness.",
    "You are the most important person in my life.",
    "I will always be here to support and protect you.",
    "Your love is the light that guides my path.",
    "Being with you is the greatest joy of my life.",
    "You are my reason for smiling every day.",
    "I love you more than words can express.",
    "Your presence makes everything better.",
    "I am grateful for every moment with you.",
    "Your love is a precious gift.",
    "With you, I feel like I can face anything.",
    "You are the person I want to spend forever with.",
    "Your happiness is what matters most to me.",
    "I love you more than I can ever show.",
    "Being with you is my favorite place to be.",
    "You are my source of daily joy.",
    "Every moment with you is a blessing.",
    "I will always be here to listen and support you.",
    "Your love makes everything worthwhile.",
    "With you, life is full of joy and laughter.",
    "You are the reason for my happiness.",
    "I love you more each day.",
    "Being with you is my greatest joy.",
    "You are my anchor in the storm.",
    "I am thankful for every second we share.",
    "Your smile is my favorite sight.",
    "You make every day better just by being you.",
    "I am so lucky to have you in my life.",
    "You are the reason I believe in love.",
    "I will always be here for you, no matter what.",
    "Your love is my greatest treasure.",
    "With you, I feel complete.",
    "You make my life brighter and more beautiful.",
    "I am grateful for every moment we have together.",
    "Your presence is my greatest comfort.",
    "Being with you makes everything feel right.",
    "You are the best part of my life.",
    "I love you more than words can express.",
    "Every day with you is a new adventure.",
    "Your love fills my heart with joy.",
    "I will always be here to support and protect you.",
    "You are my reason for waking up with a smile.",
    "With you, everything feels possible.",
    "I am so thankful for you and all that you bring to my life.",
    "Your love is the light that guides my way.",
    "Being with you is the most wonderful thing in the world.",
    "You are the reason my heart is full.",
    "I love you more with each passing day.",
    "Every moment with you is a gift.",
    "Your presence makes my world complete.",
    "I am here for you, always and forever.",
    "Your love is a beautiful blessing in my life.",
    "Being with you makes everything feel right.",
    "You are my greatest joy and happiness.",
    "I love you more than you can ever know.",
    "Your smile is my daily sunshine.",
    "With you, life is full of love and laughter.",
    "You are my everything.",
    "I am grateful for each moment we share.",
    "Your love makes me feel special and cherished.",
    "Being with you is my greatest joy.",
    "I love you more than words can say.",
    "Every day with you is an adventure.",
    "Your presence is my greatest comfort.",
    "I am thankful for you every single day.",
    "You make my heart so happy.",
    "I will always be here for you, no matter what.",
    "Your love is my greatest gift.",
    "With you, life is brighter and more joyful.",
    "You are the best part of my life.",
    "I love you more than words can express.",
    "Every moment with you is precious.",
    "Your presence makes everything better.",
    "I am grateful for you and all that you are.",
    "You bring so much joy into my life.",
    "Being with you makes every day brighter.",
    "I love you more each day.",
    "Your love is my greatest blessing.",
    "With you, I feel like I can achieve anything.",
    "You are my everything.",
    "I am thankful for every second we share together.",
    "Your smile lights up my world.",
    "I am so lucky to have you in my life.",
    "Your love makes my heart full.",
    "Being with you is my greatest joy.",
    "I love you more than words can say.",
    "Every day with you is a gift.",
    "Your presence makes everything feel right.",
    "I am grateful for you and all that you bring to my life.",
    "You are my source of happiness.",
    "With you, life is full of love and joy.",
    "I love you more than you know.",
    "Every moment with you is special.",
    "Your presence is my greatest comfort.",
    "I am thankful for you every day.",
    "You make my heart sing with happiness.",
    "I will always be here for you, no matter what.",
    "Your love is my greatest treasure.",
    "With you, life is full of possibilities.",
    "You are the best part of my life.",
    "I love you more than words can express.",
    "Every day with you is a new adventure.",
    "Your presence makes my world complete.",
    "I am grateful for every moment with you.",
    "Your love is my greatest joy.",
    "Being with you is the best part of my day.",
    "I love you more each day.",
    "You make everything better just by being you.",
    "I am thankful for you and all that you do.",
    "Your love fills my heart with happiness.",
    "With you, life is full of love and laughter.",
    "You are my reason for living.",
    "I love you more than words can express.",
    "Every moment with you is a blessing.",
    "Your presence makes everything feel right.",
    "I am grateful for you and all that you are.",
    "Being with you makes my heart full.",
    "You bring so much joy into my life.",
    "I love you more each day.",
    "Your love is my greatest blessing.",
    "With you, life is complete.",
    "You are the best part of my life.",
    "I am thankful for every moment we share together.",
    "Your smile is my daily joy.",
    "Being with you is my greatest joy.",
    "I love you more than you know.",
    "Every day with you is a new adventure.",
    "Your presence makes everything better.",
    "I am grateful for you and all that you bring to my life.",
    "You make my heart so happy.",
    "I will always be here for you, no matter what.",
    "Your love is my greatest gift.",
    "With you, life is brighter and more joyful.",
    "You are the best part of my day.",
    "I love you more than words can express.",
    "Every moment with you is precious.",
    "Your presence makes everything feel right.",
    "I am thankful for you and all that you are.",
    "Being with you makes my heart full.",
    "You bring so much joy into my life.",
    "I love you more each day.",
    "Your love is my greatest blessing.",
    "With you, life is complete.",
    "You are my everything.",
    "I am grateful for every moment we share together."
  ];

  const button = document.getElementById('generate-btn');
  const messageParagraph = document.getElementById('message');

  button.addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * messages.length);
    messageParagraph.textContent = messages[randomIndex];
  });
});